### ISSUE TITLE
Route [lumki.user.roles.edit] not defined Error

### ISSUE THREAD

**Issue by carlosjac** [kineticamobile/lumki#1]
Hi,
I navigate to /lumki/users 
I get 

ErrorException
Route [lumki.user.roles.edit] not defined. (View: /var/www/html/vendor/kineticamobile/lumki/resources/views/users/index.blade.php)

Any clue?

**Comment by raultm** [comment]
Thanks for report the issue.

We did some changes to fit the package in a customers' application withour jetstream.

Thanks to @randymfournier for updating the routes.

I checked the package in a fresh install of a jetstream project. Everything works smoothly.
-Create Permission
-Create Role
-Assign Permission To Role
-Assign Role to User
