### ISSUE TITLE
Add the permission access field to the config

### ISSUE THREAD

**Issue by shbov** [kineticamobile/lumki#10]
Hi, it seems to me that we need to add the ability to change the access permission to the package. Something like this:

config/lumki.php
```php
<?php

$permissionAccess = 'users.edit.*';

return [
    "prefix" => 'lumki',
    "permissionAccess" => $permissionAccess,
    "middleware" => ['web', 'auth:sanctum', 'can:'.$permissionAccess],
    'custom_fields' => [
        // [
        //     'type' => 'text',
        //     'name' => 'username',
        //     'label' => 'Username',
        //     'placeholder' => 'Username',
        // ],
    ]
];```

**Comment by raultm** [comment]
Maybe you can explain a bit more. I don't see the point to implement like this. In fact you already have the ability to change the access permission

```php
<?php

return [
    "prefix" => 'lumki',
    "permissionAccess" => $permissionAccess,
    "middleware" => ['web', 'auth:sanctum', 'can:users.edit.*'],
    ]
];```
```

Are you using config('lumki.permissionAccess') in the application? 

What's the needed of `permissionAccess` key in the config file if the package is not using it and you can modified the middlewares via config file?

I'm not rejecting the idea, I only want to visualize a few examples where it can be useful

**Comment by shbov** [comment]
Right now, we only have the option to change the middleware access permissions, but we can't change the blade @can ("user manage").

**Comment by raultm** [comment]
Ok, i get it

**Comment by raultm** [comment]
I think theses changes resolve this issue
