### ISSUE TITLE
Cant install on Laravel 10

### ISSUE THREAD

**Issue by albertobenavides** [kineticamobile/lumki#18]
I am having this errors while trying to install in Laravel 10:

- Root composer.json requires kineticamobile/lumki ^0.1.11 -> satisfiable by kineticamobile/lumki[v0.1.11].
- kineticamobile/lumki v0.1.11 requires illuminate/support ~5|~6|~7|~8|~9 -> found illuminate/support[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but these were not loaded, likely because it conflicts with another require.

**Comment by TonnyORG** [comment]
I still cannot use this on Laravel 10 (even with the version 0.1.11), is there any plans to support it?

**Comment by lsmith77** [comment]
this seems to be fixed.
