### ISSUE TITLE
Add/Delete/Modify user

### ISSUE THREAD

**Issue by darklord1807** [kineticamobile/lumki#2]

**Comment by darklord1807** [comment]
Would it be possible to also add the feature to add/delete and update a user?

**Comment by raultm** [comment]
Hello,

We appreciate your suggestion.

But... we think it's not a good idea. Why?

**User Edit Form**
The users table usually changes during the development of the project(fields added, fields edited, fields removed) so we can't do a fully customizable form to _YOUR APP_ user. But we added in config file a way to handle custom inputs in the user edit form.

**User/Delete Creation**
For applications in production the user generation/deletion usually involves some routines (run custom commands, populate fields with specific value, etc). We think this functionality is out of the context of this package.
