### ISSUE TITLE
Spanish translation for this package

### ISSUE THREAD

**Issue by carlosjac** [kineticamobile/lumki#4]
Hi!

Can you make this package multilingual?

I can translate it to Spanish.  

Thanks!!

**Comment by raultm** [comment]
We'll read the docs to localize a package. I think it is a good idea.

Gracias por la sugerencia!

**Comment by Xodus-CO** [comment]
setup only runs in spanish now.

**Comment by raultm** [comment]
Localize views & command of the package. English/Spanish
